### ISSUE TITLE
Frontend Changes for Userstory 3

### ISSUE THREAD

**Issue by carolin961** [Fabian-Anna/java-petclinic#22]
- [x] Übergreifende Suche erstellen
- [x] Wenn kein Suchbegriff eingegeben wurde, soll die Meldung "No results found" erscheinen
- [x] Ergebnisseite für Übergreifende Suche erstellen
- [x] Es werden max. 10 Ergebnisse von jeder Informationsart angezeigt
- [x] Gibt es mehr als 10 Ergebnisse, dann kann man +10 hinzufügen
- [x] Links zu:
- [x] Owner Detail
- [x] Pet Edit
- [x] Edit Vet
- [x] Edit Visit

**Comment by carolin961** [comment]
- [ ] add tests

**Comment by Fabian-Anna** [comment]
Nicht mehr genug Zeit für eine vollständige Testabdeckung
